
import { AISite } from './types';

export const AI_SITES: AISite[] = [
  {
    id: 'chatgpt',
    name: 'ChatGPT',
    description: 'Conversational AI by OpenAI, versatile for text generation and understanding.',
    url: 'https://chat.openai.com/',
    logoSeed: 'chatgpt_logo_seed_ai',
    tags: ['General', 'OpenAI', 'Popular'],
  },
  {
    id: 'gemini',
    name: 'Gemini',
    description: 'Google\'s powerful multimodal AI model for chat and advanced reasoning.',
    url: 'https://gemini.google.com/app',
    logoSeed: 'gemini_logo_seed_ai',
    tags: ['General', 'Google', 'Multimodal'],
  },
  {
    id: 'aistudio',
    name: 'Google AI Studio',
    description: 'Develop with Google\'s generative AI models. Ideal for prototyping.',
    url: 'https://aistudio.google.com/',
    logoSeed: 'aistudio_logo_seed_ai',
    tags: ['Development', 'Google', 'Gemini API'],
  },
  {
    id: 'claude',
    name: 'Claude',
    description: 'AI assistant by Anthropic, focused on helpfulness and safety.',
    url: 'https://claude.ai/',
    logoSeed: 'claude_logo_seed_ai',
    tags: ['General', 'Anthropic', 'Safety'],
  },
  {
    id: 'perplexity',
    name: 'Perplexity AI',
    description: 'AI-powered search engine providing answers with cited sources.',
    url: 'https://www.perplexity.ai/',
    logoSeed: 'perplexity_logo_seed_ai',
    tags: ['Search', 'Research', 'Citations'],
  },
  {
    id: 'poe',
    name: 'Poe by Quora',
    description: 'Access multiple AI chatbots like ChatGPT, Claude, and more on one platform.',
    url: 'https://poe.com/',
    logoSeed: 'poe_logo_seed_ai',
    tags: ['Platform', 'Multi-Model'],
  },
  {
    id: 'huggingchat',
    name: 'HuggingChat',
    description: 'Open-source AI chat models hosted by Hugging Face community.',
    url: 'https://huggingface.co/chat/',
    logoSeed: 'huggingchat_logo_seed_ai',
    tags: ['Open Source', 'Community'],
  },
  {
    id: 'copilot',
    name: 'Microsoft Copilot',
    description: 'Microsoft\'s AI companion integrated into its products, using advanced models.',
    url: 'https://copilot.microsoft.com/',
    logoSeed: 'copilot_logo_seed_ai',
    tags: ['General', 'Microsoft', 'Productivity'],
  },
  {
    id: 'manusai',
    name: 'Manus AI (Example)',
    description: 'Hypothetical AI platform for specialized intelligent automation tasks. (Link placeholder)',
    url: '#manus-ai-example',
    logoSeed: 'manusai_logo_seed',
    tags: ['Specialized', 'Automation', 'Example'],
  },
  {
    id: 'macroai',
    name: 'Macro AI (Example)',
    description: 'Conceptual AI tool for automating complex workflows and processes. (Link placeholder)',
    url: '#macro-ai-example',
    logoSeed: 'macroai_logo_seed',
    tags: ['Workflow', 'Productivity', 'Example'],
  },
];
